export const FETCHING_DATA = "FETCHING_DATA";

export const FETCHING_DATA_SUCCESS = "FETCHING_DATA_SUCCESS";

export const FETCHING_DATA_FAILURE = "FETCHING_DATA_FAILURE";

export const FILTER_MOVIES_BY_GENRES = "FILTER_MOVIES_BY_GENRES";

export const FILTER_MOVIES_BY_VOTE = "FILTER_MOVIES_BY_VOTE";
